// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messagedata.proto

package protobuf;

public final class ClientMessageData {
  private ClientMessageData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.MessageData.MessageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dataStr = 1;</code>
     */
    java.lang.String getDataStr();
    /**
     * <code>string dataStr = 1;</code>
     */
    com.google.protobuf.ByteString
        getDataStrBytes();

    /**
     * <code>int32 dataNum = 2;</code>
     */
    int getDataNum();
  }
  /**
   * Protobuf type {@code protobuf.MessageData.MessageData}
   */
  public  static final class MessageData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.MessageData.MessageData)
      MessageDataOrBuilder {
    // Use MessageData.newBuilder() to construct.
    private MessageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageData() {
      dataStr_ = "";
      dataNum_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MessageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              dataStr_ = s;
              break;
            }
            case 16: {

              dataNum_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.ClientMessageData.internal_static_protobuf_MessageData_MessageData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.ClientMessageData.internal_static_protobuf_MessageData_MessageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.ClientMessageData.MessageData.class, protobuf.ClientMessageData.MessageData.Builder.class);
    }

    public static final int DATASTR_FIELD_NUMBER = 1;
    private volatile java.lang.Object dataStr_;
    /**
     * <code>string dataStr = 1;</code>
     */
    public java.lang.String getDataStr() {
      java.lang.Object ref = dataStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataStr_ = s;
        return s;
      }
    }
    /**
     * <code>string dataStr = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataStrBytes() {
      java.lang.Object ref = dataStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATANUM_FIELD_NUMBER = 2;
    private int dataNum_;
    /**
     * <code>int32 dataNum = 2;</code>
     */
    public int getDataNum() {
      return dataNum_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDataStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataStr_);
      }
      if (dataNum_ != 0) {
        output.writeInt32(2, dataNum_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDataStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataStr_);
      }
      if (dataNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dataNum_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.ClientMessageData.MessageData)) {
        return super.equals(obj);
      }
      protobuf.ClientMessageData.MessageData other = (protobuf.ClientMessageData.MessageData) obj;

      boolean result = true;
      result = result && getDataStr()
          .equals(other.getDataStr());
      result = result && (getDataNum()
          == other.getDataNum());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATASTR_FIELD_NUMBER;
      hash = (53 * hash) + getDataStr().hashCode();
      hash = (37 * hash) + DATANUM_FIELD_NUMBER;
      hash = (53 * hash) + getDataNum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.ClientMessageData.MessageData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.ClientMessageData.MessageData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.ClientMessageData.MessageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.ClientMessageData.MessageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.ClientMessageData.MessageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.ClientMessageData.MessageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.ClientMessageData.MessageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.ClientMessageData.MessageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.ClientMessageData.MessageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.ClientMessageData.MessageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.ClientMessageData.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.ClientMessageData.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.ClientMessageData.MessageData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.MessageData.MessageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.MessageData.MessageData)
        protobuf.ClientMessageData.MessageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.ClientMessageData.internal_static_protobuf_MessageData_MessageData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.ClientMessageData.internal_static_protobuf_MessageData_MessageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.ClientMessageData.MessageData.class, protobuf.ClientMessageData.MessageData.Builder.class);
      }

      // Construct using protobuf.ClientMessageData.MessageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        dataStr_ = "";

        dataNum_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.ClientMessageData.internal_static_protobuf_MessageData_MessageData_descriptor;
      }

      public protobuf.ClientMessageData.MessageData getDefaultInstanceForType() {
        return protobuf.ClientMessageData.MessageData.getDefaultInstance();
      }

      public protobuf.ClientMessageData.MessageData build() {
        protobuf.ClientMessageData.MessageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.ClientMessageData.MessageData buildPartial() {
        protobuf.ClientMessageData.MessageData result = new protobuf.ClientMessageData.MessageData(this);
        result.dataStr_ = dataStr_;
        result.dataNum_ = dataNum_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.ClientMessageData.MessageData) {
          return mergeFrom((protobuf.ClientMessageData.MessageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.ClientMessageData.MessageData other) {
        if (other == protobuf.ClientMessageData.MessageData.getDefaultInstance()) return this;
        if (!other.getDataStr().isEmpty()) {
          dataStr_ = other.dataStr_;
          onChanged();
        }
        if (other.getDataNum() != 0) {
          setDataNum(other.getDataNum());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.ClientMessageData.MessageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.ClientMessageData.MessageData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object dataStr_ = "";
      /**
       * <code>string dataStr = 1;</code>
       */
      public java.lang.String getDataStr() {
        java.lang.Object ref = dataStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dataStr = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataStrBytes() {
        java.lang.Object ref = dataStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dataStr = 1;</code>
       */
      public Builder setDataStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dataStr = 1;</code>
       */
      public Builder clearDataStr() {
        
        dataStr_ = getDefaultInstance().getDataStr();
        onChanged();
        return this;
      }
      /**
       * <code>string dataStr = 1;</code>
       */
      public Builder setDataStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataStr_ = value;
        onChanged();
        return this;
      }

      private int dataNum_ ;
      /**
       * <code>int32 dataNum = 2;</code>
       */
      public int getDataNum() {
        return dataNum_;
      }
      /**
       * <code>int32 dataNum = 2;</code>
       */
      public Builder setDataNum(int value) {
        
        dataNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dataNum = 2;</code>
       */
      public Builder clearDataNum() {
        
        dataNum_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.MessageData.MessageData)
    }

    // @@protoc_insertion_point(class_scope:protobuf.MessageData.MessageData)
    private static final protobuf.ClientMessageData.MessageData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.ClientMessageData.MessageData();
    }

    public static protobuf.ClientMessageData.MessageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageData>
        PARSER = new com.google.protobuf.AbstractParser<MessageData>() {
      public MessageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageData> getParserForType() {
      return PARSER;
    }

    public protobuf.ClientMessageData.MessageData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_MessageData_MessageData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_MessageData_MessageData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021messagedata.proto\022\024protobuf.MessageDat" +
      "a\"/\n\013MessageData\022\017\n\007dataStr\030\001 \001(\t\022\017\n\007dat" +
      "aNum\030\002 \001(\005B\035\n\010protobufB\021ClientMessageDat" +
      "ab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_MessageData_MessageData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_MessageData_MessageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_MessageData_MessageData_descriptor,
        new java.lang.String[] { "DataStr", "DataNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
