// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: messagedata.proto

package protobuf;

public final class ProtobufMessage {
  private ProtobufMessage() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface ProtobufDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.MessageData.ProtobufData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string dataString = 1;</code>
     */
    java.lang.String getDataString();

    /**
     * <code>string dataString = 1;</code>
     */
    com.google.protobuf.ByteString getDataStringBytes();

    /**
     * <code>int32 dataNumber = 2;</code>
     */
    int getDataNumber();
  }
  /**
   * Protobuf type {@code protobuf.MessageData.ProtobufData}
   */
  public static final class ProtobufData extends com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.MessageData.ProtobufData)
      ProtobufDataOrBuilder {
    // Use ProtobufData.newBuilder() to construct.
    private ProtobufData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private ProtobufData() {
      dataString_ = "";
      dataNumber_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private ProtobufData(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              dataString_ = s;
              break;
            }
            case 16: {

              dataNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return protobuf.ProtobufMessage.internal_static_protobuf_MessageData_ProtobufData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return protobuf.ProtobufMessage.internal_static_protobuf_MessageData_ProtobufData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(protobuf.ProtobufMessage.ProtobufData.class,
              protobuf.ProtobufMessage.ProtobufData.Builder.class);
    }

    public static final int DATASTRING_FIELD_NUMBER = 1;
    private volatile java.lang.Object dataString_;

    /**
     * <code>string dataString = 1;</code>
     */
    public java.lang.String getDataString() {
      java.lang.Object ref = dataString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      }
      else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataString_ = s;
        return s;
      }
    }

    /**
     * <code>string dataString = 1;</code>
     */
    public com.google.protobuf.ByteString getDataStringBytes() {
      java.lang.Object ref = dataString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        dataString_ = b;
        return b;
      }
      else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATANUMBER_FIELD_NUMBER = 2;
    private int dataNumber_;

    /**
     * <code>int32 dataNumber = 2;</code>
     */
    public int getDataNumber() {
      return dataNumber_;
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!getDataStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataString_);
      }
      if (dataNumber_ != 0) {
        output.writeInt32(2, dataNumber_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (!getDataStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataString_);
      }
      if (dataNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, dataNumber_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof protobuf.ProtobufMessage.ProtobufData)) {
        return super.equals(obj);
      }
      protobuf.ProtobufMessage.ProtobufData other = (protobuf.ProtobufMessage.ProtobufData) obj;

      boolean result = true;
      result = result && getDataString().equals(other.getDataString());
      result = result && (getDataNumber() == other.getDataNumber());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATASTRING_FIELD_NUMBER;
      hash = (53 * hash) + getDataString().hashCode();
      hash = (37 * hash) + DATANUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getDataNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.ProtobufMessage.ProtobufData parseFrom(java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static protobuf.ProtobufMessage.ProtobufData parseFrom(java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static protobuf.ProtobufMessage.ProtobufData parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static protobuf.ProtobufMessage.ProtobufData parseFrom(com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static protobuf.ProtobufMessage.ProtobufData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static protobuf.ProtobufMessage.ProtobufData parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static protobuf.ProtobufMessage.ProtobufData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static protobuf.ProtobufMessage.ProtobufData parseFrom(java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static protobuf.ProtobufMessage.ProtobufData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static protobuf.ProtobufMessage.ProtobufData parseDelimitedFrom(java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static protobuf.ProtobufMessage.ProtobufData parseFrom(com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static protobuf.ProtobufMessage.ProtobufData parseFrom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(protobuf.ProtobufMessage.ProtobufData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code protobuf.MessageData.ProtobufData}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>implements
        // @@protoc_insertion_point(builder_implements:protobuf.MessageData.ProtobufData)
        protobuf.ProtobufMessage.ProtobufDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return protobuf.ProtobufMessage.internal_static_protobuf_MessageData_ProtobufData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return protobuf.ProtobufMessage.internal_static_protobuf_MessageData_ProtobufData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(protobuf.ProtobufMessage.ProtobufData.class,
                protobuf.ProtobufMessage.ProtobufData.Builder.class);
      }

      // Construct using protobuf.ProtobufMessage.ProtobufData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }

      public Builder clear() {
        super.clear();
        dataString_ = "";

        dataNumber_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return protobuf.ProtobufMessage.internal_static_protobuf_MessageData_ProtobufData_descriptor;
      }

      public protobuf.ProtobufMessage.ProtobufData getDefaultInstanceForType() {
        return protobuf.ProtobufMessage.ProtobufData.getDefaultInstance();
      }

      public protobuf.ProtobufMessage.ProtobufData build() {
        protobuf.ProtobufMessage.ProtobufData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.ProtobufMessage.ProtobufData buildPartial() {
        protobuf.ProtobufMessage.ProtobufData result = new protobuf.ProtobufMessage.ProtobufData(this);
        result.dataString_ = dataString_;
        result.dataNumber_ = dataNumber_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.ProtobufMessage.ProtobufData) {
          return mergeFrom((protobuf.ProtobufMessage.ProtobufData) other);
        }
        else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.ProtobufMessage.ProtobufData other) {
        if (other == protobuf.ProtobufMessage.ProtobufData.getDefaultInstance())
          return this;
        if (!other.getDataString().isEmpty()) {
          dataString_ = other.dataString_;
          onChanged();
        }
        if (other.getDataNumber() != 0) {
          setDataNumber(other.getDataNumber());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        protobuf.ProtobufMessage.ProtobufData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.ProtobufMessage.ProtobufData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object dataString_ = "";

      /**
       * <code>string dataString = 1;</code>
       */
      public java.lang.String getDataString() {
        java.lang.Object ref = dataString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataString_ = s;
          return s;
        }
        else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string dataString = 1;</code>
       */
      public com.google.protobuf.ByteString getDataStringBytes() {
        java.lang.Object ref = dataString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          dataString_ = b;
          return b;
        }
        else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string dataString = 1;</code>
       */
      public Builder setDataString(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        dataString_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string dataString = 1;</code>
       */
      public Builder clearDataString() {

        dataString_ = getDefaultInstance().getDataString();
        onChanged();
        return this;
      }

      /**
       * <code>string dataString = 1;</code>
       */
      public Builder setDataStringBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        dataString_ = value;
        onChanged();
        return this;
      }

      private int dataNumber_;

      /**
       * <code>int32 dataNumber = 2;</code>
       */
      public int getDataNumber() {
        return dataNumber_;
      }

      /**
       * <code>int32 dataNumber = 2;</code>
       */
      public Builder setDataNumber(int value) {

        dataNumber_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int32 dataNumber = 2;</code>
       */
      public Builder clearDataNumber() {

        dataNumber_ = 0;
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:protobuf.MessageData.ProtobufData)
    }

    // @@protoc_insertion_point(class_scope:protobuf.MessageData.ProtobufData)
    private static final protobuf.ProtobufMessage.ProtobufData DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new protobuf.ProtobufMessage.ProtobufData();
    }

    public static protobuf.ProtobufMessage.ProtobufData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtobufData> PARSER =
        new com.google.protobuf.AbstractParser<ProtobufData>() {
          public ProtobufData parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                  throws com.google.protobuf.InvalidProtocolBufferException {
            return new ProtobufData(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<ProtobufData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtobufData> getParserForType() {
      return PARSER;
    }

    public protobuf.ProtobufMessage.ProtobufData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_protobuf_MessageData_ProtobufData_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_protobuf_MessageData_ProtobufData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {"\n\021messagedata.proto\022\024protobuf.MessageDat"
        + "a\"6\n\014ProtobufData\022\022\n\ndataString\030\001 \001(\t\022\022\n"
        + "\ndataNumber\030\002 \001(\005B\033\n\010protobufB\017ProtobufM" + "essageb\006proto3"};
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
    internal_static_protobuf_MessageData_ProtobufData_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_MessageData_ProtobufData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_protobuf_MessageData_ProtobufData_descriptor,
            new java.lang.String[] {"DataString", "DataNumber",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
